# https://github.com/knojector/SteamAuthenticationBundle for configuration documentation
knojector_steam_authentication:
    api_key: "%env(STEAM_API_KEY)%"
    login_route: 'login'
    login_redirect: 'index'
    user_class: App\Entity\User
    request_validator_class: App\Security\OpenIdRequestValidator
